NAME = out
CC = c++
CFLAGS = -g -Wall -Wextra -Werror -std=c++98
SRC = \
	main.cpp


OBJS = $(addprefix $(OBJ_DIR)/, $(SRC:.cpp=.o))
OBJ_DIR = ./objs

all: $(NAME)

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

$(OBJ_DIR)/%.o: %.cpp | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@ 

$(NAME): format $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

format:
	find -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format --style=Google -i

test: 
	./$(NAME)

run: re test

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all fclean clean re test run format
